version: '3.6'
services:
  api1: &api
    build: ./
    tty: true
    stdin_open: true
    privileged: true
    env_file:
      - '.env.development'
    environment:
      RAILS_MASTER_KEY: 168ab5c7135a6b3ba29432e6afa8f919
    hostname: api1
    expose:
      - "3000"
    networks:
      - clockwisework

  api2:
    <<: *api
    hostname: api2

  nginx: # Load Balancer
      image: docker.io/nginx:latest
      command: ["nginx", "-g", "daemon off;"]
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf:ro
      depends_on:
        - api1
        - api2
      ports:
        - "8080:8080"
      networks:
        - clockwisework

networks:
  clockwisework:
    external: true

