version: '3.6'

services:
  db_postgres:
    image: 'docker.io/postgres:15.2-alpine'
    volumes:
      - '../volumes/clock-wise-work/db_postgres:/var/lib/postgresql/data'
    env_file:
      - '.env.development'
    ports:
      - '5432:5432'
    networks:
      - clockwisework
  redis:
    image: docker.io/redis:latest
    hostname: redis
    command: redis-server --save "" --appendonly no
    network_mode: host
    ports:
        - "6379:6379"

networks:
  clockwisework:
    external: true