default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  host: db_postgres

development:
  <<: *default
  database: <%= ENV["POSTGRES_DATABASE"] %>_development

test:
  <<: *default
  database: <%= ENV["POSTGRES_DATABASE"] %>_test

production:
  <<: *default
  database: <%= ENV["POSTGRES_DATABASE"] %>